DROP DATABASE IF EXISTS ECOMDB;

CREATE DATABASE ECOMDB;

USE ECOMDB;

-- TABLA USUARIO
CREATE TABLE USUARIO (
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'CLIENTE',
    APELLIDO VARCHAR(100) DEFAULT 'GENERICO',
    EMAIL VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20),
    CONTRASENIA VARCHAR(100),
    TIPO_USUARIO VARCHAR(100),
    FECHA_REGISTRO DATETIME,
    ULTIMO_ACCESO DATETIME
);

-- TABLA PRODUCTO
CREATE TABLE PRODUCTO (
	IDPRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    PRECIO INT,
    IDCATEGORIA INT,
    IDSUBCATEGORIA INT,
    IDTIENDA INT,
    DETALLE VARCHAR(100),
    CANTIDAD INT,
    STOCK BOOLEAN,
    FECHA_AGREGADO DATETIME,
    IMAGENES VARCHAR(100)
);

-- TABLA CARRITO 
CREATE TABLE CARRITO (
	IDCARRITO INT PRIMARY KEY AUTO_INCREMENT,
    IDUSUARIO INT,
    FECHA_CREACION DATETIME,
    ESTADO BOOLEAN,
    TOTAL INT
);

-- TABLA DETALLE_CARRITO
CREATE TABLE DETALLE_CARRITO (
    IDCARRITO INT,
    IDPRODUCTO INT,
    CANTIDAD INT
);

-- TABLA EMPLEADOS 
CREATE TABLE EMPLEADO (
	IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    IDTIENDA INT,
    PUESTO VARCHAR(100),
    SUELDO INT,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR(100) NOT NULL,
    FECHA_CONTRATACION DATETIME
);

-- TABLA TIENDA
CREATE TABLE TIENDA (
	IDTIENDA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR(100) NOT NULL
);

-- TABLA TRN
CREATE TABLE TRN (
	IDTRN INT PRIMARY KEY AUTO_INCREMENT,
    IDPRODUCTO INT,
    IDTIENDA_ORIGEN INT,
    IDTIENDA_DESTINO INT,
    CANTIDAD INT,
    FECHA_TRN DATETIME,
    OBSERVACIONES VARCHAR(100)
);

-- TABLA CATEGORIA
CREATE TABLE CATEGORIA (
	IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100)
);

-- TABLA SUBCATEGORIA
CREATE TABLE SUBCATEGORIA (
	IDSUBCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    IDCATEGORIA INT
);

-- TABLA ORDEN DE VENTA 
CREATE TABLE ORDENDEVENTA (
	IDORDEN INT PRIMARY KEY AUTO_INCREMENT,
    IDUSUARIO INT,
    FECHA_CREACION DATETIME,
    ESTADO BOOLEAN,
    DIRECCION_ENVIO VARCHAR(255),
    IDCARRITO INT
);


-- FOREIGNS KEYS DEFINITION

-- PRODUCTOS
ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_CATEGORIA
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA);

ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_SUBCATEGORIA
    FOREIGN KEY (IDSUBCATEGORIA) REFERENCES SUBCATEGORIA(IDSUBCATEGORIA);
    
ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_TIENDA
    FOREIGN KEY (IDTIENDA) REFERENCES TIENDA(IDTIENDA);
    
-- CARRITO
ALTER TABLE CARRITO
	ADD CONSTRAINT FK_CARRITO_USUARIO
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO);
  
-- DETALLE CARRITO
ALTER TABLE DETALLE_CARRITO
	ADD CONSTRAINT FK_DETALLECARRITO_CARRITO
    FOREIGN KEY (IDCARRITO) REFERENCES CARRITO(IDCARRITO);
  
ALTER TABLE DETALLE_CARRITO
	ADD CONSTRAINT FK_DETALLECARRITO_PRODUCTO
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);
   
-- EMPLEADOS
ALTER TABLE EMPLEADO
	ADD CONSTRAINT FK_EMPLEADO_TIENDA
    FOREIGN KEY (IDTIENDA) REFERENCES TIENDA(IDTIENDA);
    
-- TRN
ALTER TABLE TRN
	ADD CONSTRAINT FK_TRN_PRODUCTO
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);

ALTER TABLE TRN
	ADD CONSTRAINT FK_TRN_TIENDAORIGEN
    FOREIGN KEY (IDTIENDA_ORIGEN) REFERENCES TIENDA(IDTIENDA);
    
ALTER TABLE TRN
	ADD CONSTRAINT FK_TRN_TIENDADESTINO
    FOREIGN KEY (IDTIENDA_DESTINO) REFERENCES TIENDA(IDTIENDA);
    
-- SUBCATEGORIAS
ALTER TABLE SUBCATEGORIA
	ADD CONSTRAINT FK_SUBCATEGORIA_CATEGORIA
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA);
  
-- ORDENES DE VENTA
ALTER TABLE ORDENDEVENTA
	ADD CONSTRAINT FK_ORDENDEVENTA_USUARIO
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO);
    
ALTER TABLE ORDENDEVENTA
	ADD CONSTRAINT FK_ORDENDEVENTA_CARRITO
    FOREIGN KEY (IDCARRITO) REFERENCES CARRITO(IDCARRITO);