-- GENERAR EL DDL

DROP DATABASE IF EXISTS TRINITY_ECOMMERCE;

CREATE DATABASE TRINITY_ECOMMERCE;

USE TRINITY_ECOMMERCE;

-- TABLA USUARIOS
CREATE TABLE USUARIOS (
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'CLIENTE',
    APELLIDO VARCHAR(100) DEFAULT 'GENERICO',
    EMAIL VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20),
    CONTRASENIA VARCHAR(100),
    TIPO_USUARIO VARCHAR(100),
    FECHA_REGISTRO DATETIME,
    ULTIMO_ACCESO DATETIME
);

-- TABLA PRODUCTOS
CREATE TABLE PRODUCTOS (
	IDPRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    PRECIO INT,
    IDCATEGORIA INT,
    IDSUBCATEGORIA INT,
    IDTIENDA INT,
    DETALLE VARCHAR(100),
    CANTIDAD INT,
    STOCK BOOLEAN,
    FECHA_AGREGADO DATETIME,
    IMAGENES VARCHAR(100)
);

-- TABLA CARRITO 
CREATE TABLE CARRITO (
	IDCARRITO INT PRIMARY KEY AUTO_INCREMENT,
    IDUSUARIO INT,
    FECHA_CREACION DATETIME,
    ESTADO BOOLEAN
);

-- TABLA DETALLE_CARRITO
CREATE TABLE DETALLE_CARRITO (
    IDCARRITO INT,
    IDPRODUCTO INT,
    CANTIDAD INT
);

-- TABLA EMPLEADOS 
CREATE TABLE EMPLEADOS (
	IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    IDTIENDA INT,
    PUESTO VARCHAR(100),
    SUELDO INT,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR(100) NOT NULL,
    FECHA_CONTRATACION DATETIME
);

-- TABLA TIENDAS
CREATE TABLE TIENDAS (
	IDTIENDA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONO VARCHAR(100) NOT NULL
);

-- TABLA TRN
CREATE TABLE TRN (
	IDTRN INT PRIMARY KEY AUTO_INCREMENT,
    IDPRODUCTO INT,
    IDTIENDA_ORIGEN INT,
    IDTIENDA_DESTINO INT,
    CANTIDAD INT,
    FECHA_TRN DATETIME,
    OBSERVACIONES VARCHAR(100)
);

-- TABLA CATEGORIAS
CREATE TABLE CATEGORIAS (
	IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100)
);

-- TABLA SUBCATEGORIAS
CREATE TABLE SUBCATEGORIAS (
	IDSUBCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    IDCATEGORIA INT
);

-- TABLA ORDENES DE VENTA 
CREATE TABLE ORDENESDEVENTA (
	IDORDEN INT PRIMARY KEY AUTO_INCREMENT,
    IDUSUARIO INT,
    FECHA_CREACION DATETIME,
    ESTADO VARCHAR(100),
    DIRECCION_ENVIO VARCHAR(255),
    IDCARRITO INT
);


-- FOREIGNS KEYS DEFINITION

-- PRODUCTOS
ALTER TABLE PRODUCTOS
	ADD CONSTRAINT FK_PRODUCTOS_CATEGORIA
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA);

ALTER TABLE PRODUCTOS
	ADD CONSTRAINT FK_PRODUCTOS_SUBCATEGORIA
    FOREIGN KEY (IDSUBCATEGORIA) REFERENCES SUBCATEGORIAS(IDSUBCATEGORIA);
    
ALTER TABLE PRODUCTOS
	ADD CONSTRAINT FK_PRODUCTOS_TIENDAS
    FOREIGN KEY (IDTIENDA) REFERENCES TIENDAS(IDTIENDA);
    
-- CARRITO
ALTER TABLE CARRITO
	ADD CONSTRAINT FK_CARRITO_USUARIO
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO);
  
-- DETALLE CARRITO
ALTER TABLE DETALLE_CARRITO
	ADD CONSTRAINT FK_DETALLECARRITO_CARRITO
    FOREIGN KEY (IDCARRITO) REFERENCES CARRITO(IDCARRITO);
  
ALTER TABLE DETALLE_CARRITO
	ADD CONSTRAINT FK_DETALLECARRITO_PRODUCTOS
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO);
   
-- EMPLEADOS
ALTER TABLE EMPLEADOS
	ADD CONSTRAINT FK_EMPLEADOS_TIENDAS
    FOREIGN KEY (IDTIENDA) REFERENCES TIENDAS(IDTIENDA);
    
-- TRN
ALTER TABLE TRN
	ADD CONSTRAINT FK_TRN_PRODUCTOS
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO);

ALTER TABLE TRN
	ADD CONSTRAINT FK_TRN_TIENDASORIGEN
    FOREIGN KEY (IDTIENDA_ORIGEN) REFERENCES TIENDAS(IDTIENDA);
    
ALTER TABLE TRN
	ADD CONSTRAINT FK_TRN_TIENDASDESTINO
    FOREIGN KEY (IDTIENDA_DESTINO) REFERENCES TIENDAS(IDTIENDA);
    
-- SUBCATEGORIAS
ALTER TABLE SUBCATEGORIAS
	ADD CONSTRAINT FK_SUBCATEGORIAS_CATEGORIAS
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA);
  
-- ORDENES DE VENTA
ALTER TABLE ORDENESDEVENTA
	ADD CONSTRAINT FK_ORDENESDEVENTA_USUARIO
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO);
    
ALTER TABLE ORDENESDEVENTA
	ADD CONSTRAINT FK_ORDENESDEVENTA_CARRITO
    FOREIGN KEY (IDCARRITO) REFERENCES CARRITO(IDCARRITO);